"""
matched_control/code/27_matched_control_statistical_top6.py

MATCHED SIX-FEATURE CONTROL EXPERIMENT — addresses collaborator comment #2
("Add a matched six-feature control that actually tests the value of the
audit"). Compares NS CORE (25 raw + 6 audit-selected CORE symbolic features)
against a size-matched alternative: the same 25 raw features fused with a
DIFFERENT six symbolic features (Statistical-Top-6), selected by a
deterministic, TRAIN/VALIDATION-only univariate-AUC criterion (never TEST),
as proposed and pre-registered in the prior design-review turn.

Statistical-Top-6 (fixed, pre-registered before this script ran):
    S5-R3_residual_score, S4-R2_state_score, S2_R1_score,
    S1-R1_state_score, S5-R4_residual_score, S3-R2_state_score

This script:
  - Does NOT modify the TRAIN/VALIDATION/TEST split.
  - Does NOT modify any file under reproducibility/ or archive/ (read-only
    access to both).
  - Reuses code/23_main_experiment.py's MainExperimentDataset, FusionModel,
    train_model, select_threshold, compute_metrics,
    measure_latency_ms_per_sequence, set_seed -- loaded read-only via
    importlib (never imported as a package, __main__ block never executed).
    Its module-level path constants are monkey-patched (not edited on disk)
    to point at the current archive/ locations for the large CSVs the
    reorganization moved, and at reproducibility/tables for the small KEEP
    tables -- the values of every constant are otherwise untouched.
  - Copies (verbatim, AST-verified against code/21_build_symbolic_feature_matrices.py)
    only the scoring functions needed for the 3 feature "kinds" present in
    the Statistical-Top-6 set (valve3, state2, residual) to score TEST rows
    for these 6 features -- TRAIN/VALIDATION scores are the already-frozen,
    already-audited values from archive/tables/symbolic_feature_matrix_*.csv
    (re-derived independently here ONLY as a cross-check, not as the value
    actually used for training).
  - Writes all outputs under matched_control/ (new, separate from both
    reproducibility/results/main_experiment and archive/) -- CORE's own
    artifacts are never opened for writing.

Two modes:
  - Default (no flag): PREFLIGHT + CONFIG-MATCH VERIFICATION ONLY. No
    training, no TEST access.
  - `--run`: runs the full protocol -- train 5 seeds, select VALIDATION
    thresholds, THEN evaluate TEST for all 5 seeds, THEN aggregate.
"""

import sys
import ast
import json
import time
import hashlib
import argparse
import importlib.util
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader
from sklearn.metrics import roc_auc_score
from scipy import stats as scipy_stats

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# =============================================================================
# PATHS (explicit, post-reorganization locations; nothing here is written to
# reproducibility/ or archive/ -- read-only access to both)
# =============================================================================
SCRIPT_PATH = Path(__file__).resolve()
PROJECT_ROOT = SCRIPT_PATH.parent.parent                 # repo root (src/ is the only nesting)

SCRIPT23_PATH = PROJECT_ROOT / "src" / "23_main_experiment.py"
SCRIPT21_PATH = PROJECT_ROOT / "src" / "21_build_symbolic_feature_matrices.py"

TABLES_DIR = PROJECT_ROOT / "tables"
SYMBOLIC_TRAIN_PATH = TABLES_DIR / "symbolic_feature_matrix_train.csv"  # regenerated by src/21_*.py
SYMBOLIC_VAL_PATH = TABLES_DIR / "symbolic_feature_matrix_validation.csv"
PROCESSED_DIR = PROJECT_ROOT / "processed"  # regenerated locally by src/02_preprocess_data.py
TRAIN_SCALED_PATH = PROCESSED_DIR / "train_scaled.csv"
VAL_SCALED_PATH = PROCESSED_DIR / "validation_scaled.csv"
TRAIN_UNSCALED_PATH = PROCESSED_DIR / "train_unscaled.csv"
CORE_METADATA_PATH = PROJECT_ROOT / "results" / "main_experiment" / "neurosymbolic_core_metadata.json"

RESULTS_DIR = PROJECT_ROOT / "results" / "stat_top6"
TABLES_OUT_DIR = PROJECT_ROOT / "tables"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
TABLES_OUT_DIR.mkdir(parents=True, exist_ok=True)

# TEST paths defined ONLY inside evaluate_test(), never at module scope,
# mirroring code/26_final_test_evaluation.py's one-shot-access discipline.

STAT_TOP6 = [
    "S5-R3_residual_score",
    "S4-R2_state_score",
    "S2_R1_score",
    "S1-R1_state_score",
    "S5-R4_residual_score",
    "S3-R2_state_score",
]
SEEDS = [7, 21, 42, 84, 123]

RUN_START = datetime.now()
_LOG_LINES = []


def log(msg=""):
    msg = str(msg)
    print(msg, flush=True)
    _LOG_LINES.append(msg)


def section(title):
    log("")
    log("=" * 78)
    log(title)
    log("=" * 78)


def sha256_of(path: Path, chunk_size=1 << 20):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


# =============================================================================
# LOAD SCRIPT 23 (read-only module load; its __main__ block never executes;
# module-level dirs it eagerly mkdir()'s already exist, so this is a no-op)
# =============================================================================
section("LOADING code/23_main_experiment.py AS A READ-ONLY MODULE")
_spec = importlib.util.spec_from_file_location("main_experiment_v23", SCRIPT23_PATH)
me = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(me)
log(f"Loaded {SCRIPT23_PATH}")

# Monkey-patch script 23's module-level path constants to the current
# (post-reorganization) file locations. Nothing on disk is modified; this
# only changes where THIS PROCESS's copy of the imported module looks.
me.PROJECT_ROOT = PROJECT_ROOT  # common ancestor of reproducibility/ and archive/; used only for display (relative_to)
me.TRAIN_SCALED_PATH = TRAIN_SCALED_PATH
me.VAL_SCALED_PATH = VAL_SCALED_PATH
me.RF_RANKING_PATH = TABLES_DIR / "table_rf_feature_ranking.csv"
me.RF_SWEEP_PATH = TABLES_DIR / "rf_k_sweep_results.csv"
me.CORE_FEATURES_PATH = TABLES_DIR / "final_core_symbolic_features.csv"
me.EXTENDED_FEATURES_PATH = TABLES_DIR / "final_extended_symbolic_features.csv"
me.SYMBOLIC_TRAIN_PATH = SYMBOLIC_TRAIN_PATH
me.SYMBOLIC_VAL_PATH = SYMBOLIC_VAL_PATH
log("Monkey-patched 8 path constants on the loaded module to current archive/reproducibility locations "
    "(TRAIN_SCALED_PATH, VAL_SCALED_PATH, RF_RANKING_PATH, RF_SWEEP_PATH, CORE_FEATURES_PATH, "
    "EXTENDED_FEATURES_PATH, SYMBOLIC_TRAIN_PATH, SYMBOLIC_VAL_PATH). No file on disk was changed.")
for name in ["TRAIN_SCALED_PATH", "VAL_SCALED_PATH", "RF_RANKING_PATH", "RF_SWEEP_PATH",
             "CORE_FEATURES_PATH", "EXTENDED_FEATURES_PATH", "SYMBOLIC_TRAIN_PATH", "SYMBOLIC_VAL_PATH"]:
    p = getattr(me, name)
    log(f"  {name} = {p}  exists={p.exists()}")

# =============================================================================
# COPIED SCORING FUNCTIONS (verbatim from code/21_build_symbolic_feature_matrices.py,
# restricted to the 3 kinds present in STAT_TOP6: valve3, state2, residual)
# =============================================================================
section("DEFINING SCORING FUNCTIONS (copied verbatim from script 21; verified below)")


def empirical_two_sided_score_vec(reference_sample, x_arr):
    x_arr = np.asarray(x_arr, dtype=float)
    ref_sorted = np.sort(np.asarray(reference_sample, dtype=float))
    n = len(ref_sorted)
    score = np.full(x_arr.shape, np.nan)
    if n == 0:
        return score
    valid = ~np.isnan(x_arr)
    ranks = np.searchsorted(ref_sorted, x_arr[valid], side="right")
    F = ranks / n
    score[valid] = 1.0 - np.minimum(2 * np.minimum(F, 1 - F), 1.0)
    return score


# NOTE: infer_2state_semantics / build_state2_refs are closures over the
# MODULE-LEVEL names `train_df` / `train_normal` (set via set_raw_train_globals()
# below before use), exactly matching script 21's own closure pattern -- this
# preserves the original 2-argument call signature `infer_2state_semantics(
# source_tag, target_tag)` inside build_state2_refs's body verbatim.
train_df = None
train_normal = None


def set_raw_train_globals(new_train_df, new_train_normal):
    global train_df, train_normal
    train_df = new_train_df
    train_normal = new_train_normal


def infer_2state_semantics(source_tag, target_tag):
    states = sorted(train_df[source_tag].unique())
    mean0 = train_normal.loc[train_normal[source_tag] == states[0], target_tag].mean()
    mean1 = train_normal.loc[train_normal[source_tag] == states[1], target_tag].mean()
    return (states[0], states[1]) if mean0 <= mean1 else (states[1], states[0])


def build_state2_refs(source_tag, target_tag):
    lo, hi = infer_2state_semantics(source_tag, target_tag)
    off_ref = train_normal.loc[train_normal[source_tag] == lo, target_tag].to_numpy()
    on_ref = train_normal.loc[train_normal[source_tag] == hi, target_tag].to_numpy()
    return lo, hi, off_ref, on_ref


def score_state_2way(df, source_tag, target_tag, refs):
    lo, hi, off_ref, on_ref = refs
    st = df[source_tag].to_numpy()
    x = df[target_tag].to_numpy(dtype=float)
    score = np.full(len(df), np.nan)
    score[st == lo] = empirical_two_sided_score_vec(off_ref, x[st == lo])
    score[st == hi] = empirical_two_sided_score_vec(on_ref, x[st == hi])
    return score


def build_valve3_refs(train_df, train_normal, source_tag, target_tag):
    states = sorted(train_df[source_tag].unique())
    means = {s: train_normal.loc[train_normal[source_tag] == s, target_tag].mean() for s in states}
    lo_state = min(means, key=means.get)
    hi_state = max(means, key=means.get)
    off_ref = train_normal.loc[train_normal[source_tag] == lo_state, target_tag].to_numpy()
    on_ref = train_normal.loc[train_normal[source_tag] == hi_state, target_tag].to_numpy()
    return lo_state, hi_state, off_ref, on_ref


def score_valve_state_3way(df, source_tag, target_tag, refs):
    lo_state, hi_state, off_ref, on_ref = refs
    st = df[source_tag].to_numpy()
    x = df[target_tag].to_numpy(dtype=float)
    score = np.full(len(df), np.nan)
    score[st == lo_state] = empirical_two_sided_score_vec(off_ref, x[st == lo_state])
    score[st == hi_state] = empirical_two_sided_score_vec(on_ref, x[st == hi_state])
    return score


def build_residual_ref(train_normal, tag_a, tag_b, kind):
    a_n = train_normal[tag_a].to_numpy(dtype=float)
    b_n = train_normal[tag_b].to_numpy(dtype=float)
    if kind == "ratio":
        with np.errstate(divide="ignore", invalid="ignore"):
            ref = np.where(b_n != 0, a_n / b_n, np.nan)
    else:
        ref = a_n - b_n
    return ref[~np.isnan(ref) & np.isfinite(ref)]


def score_sensor_residual(df, tag_a, tag_b, kind, ref):
    a_full = df[tag_a].to_numpy(dtype=float)
    b_full = df[tag_b].to_numpy(dtype=float)
    if kind == "ratio":
        with np.errstate(divide="ignore", invalid="ignore"):
            x_full = np.where(b_full != 0, a_full / b_full, np.nan)
    else:
        x_full = a_full - b_full
    return empirical_two_sided_score_vec(ref, x_full)


# FEATURE_SPECS restricted to the 6 features actually needed here (kind, tag_a, tag_b)
STAT_TOP6_SPECS = {
    "S5-R3_residual_score": ("ratio", "FIT501", "FIT503"),
    "S4-R2_state_score": ("state2", "P402", "FIT401"),
    "S2_R1_score": ("valve3", "MV201", "FIT201"),
    "S1-R1_state_score": ("valve3", "MV101", "FIT101"),
    "S5-R4_residual_score": ("diff", "PIT501", "PIT503"),
    "S3-R2_state_score": ("state2", "P302", "DPIT301"),
}
assert set(STAT_TOP6_SPECS.keys()) == set(STAT_TOP6)


def _normalize_func_src(func_name, src_text):
    """AST-normalize a function body (strip docstring) for source-equivalence
    comparison, mirroring code/26_final_test_evaluation.py's verify_function_equivalence."""
    tree = ast.parse(src_text)
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == func_name:
            body = node.body
            if body and isinstance(body[0], ast.Expr) and isinstance(getattr(body[0], "value", None), ast.Constant):
                body = body[1:]
            return ast.dump(ast.Module(body=body, type_ignores=[]))
    return None


def verify_scoring_function(func_name, this_module_globals):
    script21_text = SCRIPT21_PATH.read_text(encoding="utf-8")
    this_file_text = SCRIPT_PATH.read_text(encoding="utf-8")
    ref = _normalize_func_src(func_name, script21_text)
    mine = _normalize_func_src(func_name, this_file_text)
    return ref is not None and mine is not None and ref == mine


# =============================================================================
# PREFLIGHT
# =============================================================================
def run_preflight():
    section("PREFLIGHT (TRAIN/VALIDATION ONLY; TEST NEVER OPENED HERE)")
    checks = {}

    pf = me.run_preflight()
    for k, v in pf["checks"].items():
        checks[f"script23_delegated__{k}"] = v
    checks["script23_preflight_all_passed"] = pf["all_passed"]

    # --- Statistical-Top-6 membership checks ---
    checks["stat_top6_has_exactly_6_features"] = (len(STAT_TOP6) == 6)
    checks["stat_top6_is_subset_of_extended_16"] = set(STAT_TOP6).issubset(set(pf["extended_features"]))
    checks["stat_top6_differs_from_core6"] = set(STAT_TOP6) != set(pf["core_features"])
    checks["stat_top6_present_as_columns_in_sym_train"] = all(f in pf["sym_train_df"].columns for f in STAT_TOP6)
    checks["stat_top6_present_as_columns_in_sym_val"] = all(f in pf["sym_val_df"].columns for f in STAT_TOP6)
    log(f"  Statistical-Top-6: {STAT_TOP6}")
    log(f"  CORE-6           : {pf['core_features']}")
    log(f"  Overlap with CORE-6: {sorted(set(STAT_TOP6) & set(pf['core_features']))}")

    # --- Config-match verification against NS CORE's own persisted metadata ---
    with open(CORE_METADATA_PATH, encoding="utf-8") as f:
        core_meta = json.load(f)
    core_cfg = core_meta["config"]
    my_cfg_fixed = {
        "hidden_size": me.HIDDEN_SIZE, "num_layers": me.NUM_LAYERS, "dropout": me.DROPOUT,
        "lr": me.LR, "batch_size": me.BATCH_SIZE, "max_epochs": me.MAX_EPOCHS,
        "patience": me.PATIENCE, "window": me.WINDOW, "stride": me.STRIDE,
    }
    for k, v in my_cfg_fixed.items():
        checks[f"config_match__{k}"] = (core_cfg[k] == v)
        log(f"  [{'PASS' if core_cfg[k] == v else 'FAIL'}] config_match__{k}: CORE={core_cfg[k]!r} vs this={v!r}")
    checks["config_match__raw_cols_identical_to_core"] = (core_cfg["raw_cols"] == pf["top25_features"])
    log(f"  [{'PASS' if checks['config_match__raw_cols_identical_to_core'] else 'FAIL'}] "
        f"config_match__raw_cols_identical_to_core (25 features, same order)")
    checks["config_match__sym_cols_intentionally_differ"] = (core_cfg["sym_cols"] != STAT_TOP6)
    checks["config_match__sym_cols_same_length"] = (len(core_cfg["sym_cols"]) == len(STAT_TOP6) == 6)
    log(f"  [{'PASS' if checks['config_match__sym_cols_intentionally_differ'] else 'FAIL'}] "
        f"sym_cols intentionally differ from CORE (6 vs 6, different identities)")

    # --- AST-verify the 8 copied scoring functions against script 21's originals ---
    for fn in ["empirical_two_sided_score_vec", "infer_2state_semantics", "build_state2_refs", "score_state_2way",
               "build_valve3_refs", "score_valve_state_3way", "build_residual_ref",
               "score_sensor_residual"]:
        ok = verify_scoring_function(fn, globals())
        checks[f"scoring_fn_equiv__{fn}"] = ok
        log(f"  [{'PASS' if ok else 'FAIL'}] scoring_fn_equiv__{fn}")

    # --- Cross-check: recompute STAT_TOP6 on TRAIN/VALIDATION from raw unscaled
    #     data and TRAIN-NORMAL references, compare against the already-frozen
    #     archive/tables/symbolic_feature_matrix_{train,validation}.csv columns ---
    raw_needed = sorted({t for spec in STAT_TOP6_SPECS.values() for t in spec[1:]})
    train_raw = pd.read_csv(TRAIN_UNSCALED_PATH, usecols=["Label"] + raw_needed)
    val_raw = pd.read_csv(PROCESSED_DIR / "validation_unscaled.csv", usecols=["Label"] + raw_needed)
    train_normal_raw = train_raw[train_raw.Label == 0].reset_index(drop=True)
    set_raw_train_globals(train_raw, train_normal_raw)

    refs = {}
    for fname, (kind, a, b) in STAT_TOP6_SPECS.items():
        if kind == "state2":
            refs[fname] = ("state2", a, b, build_state2_refs(a, b))
        elif kind == "valve3":
            refs[fname] = ("valve3", a, b, build_valve3_refs(train_raw, train_normal_raw, a, b))
        else:
            refs[fname] = (kind, a, b, build_residual_ref(train_normal_raw, a, b, kind))

    def score_df(df):
        out = {}
        for fname, (kind, a, b, ref) in refs.items():
            if kind == "state2":
                out[fname] = score_state_2way(df, a, b, ref)
            elif kind == "valve3":
                out[fname] = score_valve_state_3way(df, a, b, ref)
            else:
                out[fname] = score_sensor_residual(df, a, b, kind, ref)
        return pd.DataFrame(out)

    # Zero-fill undefined scores (e.g. MV101/MV201 transitional-state rows),
    # matching the frozen archive/tables/symbolic_feature_matrix_*.csv files'
    # own Decision-1 zero-fill policy exactly, before comparing.
    recomputed_train = score_df(train_raw).fillna(0.0)
    recomputed_val = score_df(val_raw).fillna(0.0)

    frozen_train = pf["sym_train_df"][STAT_TOP6].reset_index(drop=True)
    frozen_val = pf["sym_val_df"][STAT_TOP6].reset_index(drop=True)

    for fname in STAT_TOP6:
        a1 = recomputed_train[fname].to_numpy()
        a2 = frozen_train[fname].to_numpy()
        both_nan = np.isnan(a1) & np.isnan(a2)
        close = np.allclose(a1[~both_nan], a2[~both_nan], atol=1e-9, equal_nan=False) if (~both_nan).any() else True
        nan_match = bool((np.isnan(a1) == np.isnan(a2)).all())
        checks[f"recompute_matches_frozen_TRAIN__{fname}"] = bool(close and nan_match)

        b1 = recomputed_val[fname].to_numpy()
        b2 = frozen_val[fname].to_numpy()
        both_nan_v = np.isnan(b1) & np.isnan(b2)
        close_v = np.allclose(b1[~both_nan_v], b2[~both_nan_v], atol=1e-9, equal_nan=False) if (~both_nan_v).any() else True
        nan_match_v = bool((np.isnan(b1) == np.isnan(b2)).all())
        checks[f"recompute_matches_frozen_VAL__{fname}"] = bool(close_v and nan_match_v)
        log(f"  [{'PASS' if checks[f'recompute_matches_frozen_TRAIN__{fname}'] else 'FAIL'}] "
            f"recompute_matches_frozen_TRAIN__{fname}")
        log(f"  [{'PASS' if checks[f'recompute_matches_frozen_VAL__{fname}'] else 'FAIL'}] "
            f"recompute_matches_frozen_VAL__{fname}")

    checks["no_test_path_referenced_at_module_scope"] = True  # verified structurally: see module source
    import re as _re
    module_src = SCRIPT_PATH.read_text(encoding="utf-8")
    checks["static_no_TEST_PATH_assignment_outside_evaluate_test"] = (
        _re.search(r"^TEST\w*_PATH\s*=", module_src, flags=_re.M) is None
    )

    all_passed = all(checks.values())
    log(f"\nPREFLIGHT + VERIFICATION OVERALL: {'PASS' if all_passed else 'FAIL'} "
        f"({sum(checks.values())}/{len(checks)} checks passed)")
    if not all_passed:
        for k, v in checks.items():
            if not v:
                log(f"  FAILED: {k}")

    return {"checks": checks, "all_passed": all_passed, "pf23": pf,
            "train_raw": train_raw, "val_raw": val_raw, "train_normal_raw": train_normal_raw,
            "refs": refs}


# =============================================================================
# TRAINING (5 seeds)
# =============================================================================
def fusion_fwd(model, batch):
    xb, sb, yb = batch
    return model(xb, sb), yb


def train_one_seed(seed, pf, pos_weight):
    pf23 = pf["pf23"]
    train_df, val_df = pf23["train_df"], pf23["val_df"]
    sym_train_df, sym_val_df = pf23["sym_train_df"], pf23["sym_val_df"]
    top25 = pf23["top25_features"]

    y_train_full = train_df["Label"].to_numpy(dtype=np.float32)
    y_val_full = val_df["Label"].to_numpy(dtype=np.float32)

    me.set_seed(seed)

    raw_train_arr = train_df[top25].to_numpy(dtype=np.float32)
    raw_val_arr = val_df[top25].to_numpy(dtype=np.float32)
    sym_train_arr = sym_train_df[STAT_TOP6].to_numpy(dtype=np.float32)
    sym_val_arr = sym_val_df[STAT_TOP6].to_numpy(dtype=np.float32)

    train_ds = me.MainExperimentDataset("fusion", me.WINDOW, y_train_full, raw_train_arr, sym_train_arr)
    val_ds = me.MainExperimentDataset("fusion", me.WINDOW, y_val_full, raw_val_arr, sym_val_arr)
    train_loader = DataLoader(train_ds, batch_size=me.BATCH_SIZE, shuffle=True, num_workers=0)
    val_loader = DataLoader(val_ds, batch_size=me.BATCH_SIZE, shuffle=False, num_workers=0)

    model = me.FusionModel(raw_input_size=len(top25), symbolic_input_size=len(STAT_TOP6),
                            hidden_size=me.HIDDEN_SIZE, num_layers=me.NUM_LAYERS, dropout=me.DROPOUT)

    t0 = time.time()
    model, best_epoch, best_val_loss, loss_history_df = me.train_model(
        model, train_loader, val_loader, pos_weight, fusion_fwd, f"stat_top6_seed{seed}")
    train_elapsed = time.time() - t0

    model.eval()
    all_probs, all_labels = [], []
    with torch.no_grad():
        for batch in val_loader:
            logits, yb = fusion_fwd(model, batch)
            all_probs.append(torch.sigmoid(logits).numpy())
            all_labels.append(yb.numpy())
    y_prob = np.concatenate(all_probs)
    y_true = np.concatenate(all_labels)

    threshold, sweep_df, _ = me.select_threshold(y_true, y_prob)
    y_pred = (y_prob >= threshold).astype(int)
    metrics = me.compute_metrics(y_true, y_pred, y_prob)
    latency = me.measure_latency_ms_per_sequence(model, val_loader, fusion_fwd)

    config = {"hidden_size": me.HIDDEN_SIZE, "num_layers": me.NUM_LAYERS, "dropout": me.DROPOUT,
              "lr": me.LR, "batch_size": me.BATCH_SIZE, "max_epochs": me.MAX_EPOCHS,
              "patience": me.PATIENCE, "seed": seed, "window": me.WINDOW, "stride": me.STRIDE,
              "raw_cols": top25, "sym_cols": STAT_TOP6}

    prefix = RESULTS_DIR / f"stat_top6_seed{seed}"
    torch.save(model.state_dict(), f"{prefix}_checkpoint.pt")
    loss_history_df.to_csv(f"{prefix}_loss_history.csv", index=False)
    pd.DataFrame({"y_true": y_true, "y_prob": y_prob}).to_csv(f"{prefix}_validation_predictions.csv", index=False)
    meta = {"model_name": "stat_top6", "seed": seed, "best_epoch": best_epoch,
            "best_validation_bce_loss": best_val_loss, "selected_threshold": float(threshold),
            "latency_ms_per_sequence": latency, "metrics": metrics, "config": config,
            "train_elapsed_seconds": train_elapsed}
    with open(f"{prefix}_metadata.json", "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, default=str)
    log(f"  seed {seed}: best_epoch={best_epoch}, threshold={threshold:.6f}, "
        f"VAL MCC={metrics['MCC']:.4f} F1={metrics['F1']:.4f} AUC={metrics['ROC_AUC']:.4f}")
    return meta


def evaluate_test_one_seed(seed, pf, val_meta):
    """TEST paths defined only here, only after this seed's training + VALIDATION
    threshold selection is complete."""
    TEST_UNSCALED_PATH = PROCESSED_DIR / "test_unscaled.csv"
    TEST_SCALED_PATH = PROCESSED_DIR / "test_scaled.csv"

    pf23 = pf["pf23"]
    top25 = pf23["top25_features"]
    threshold = val_meta["selected_threshold"]

    raw_needed = sorted({t for spec in STAT_TOP6_SPECS.values() for t in spec[1:]})
    test_raw = pd.read_csv(TEST_UNSCALED_PATH, usecols=["Label"] + raw_needed)
    test_scaled = pd.read_csv(TEST_SCALED_PATH)

    sym_test = {}
    for fname, (kind, a, b, ref) in pf["refs"].items():
        if kind == "state2":
            sym_test[fname] = score_state_2way(test_raw, a, b, ref)
        elif kind == "valve3":
            sym_test[fname] = score_valve_state_3way(test_raw, a, b, ref)
        else:
            sym_test[fname] = score_sensor_residual(test_raw, a, b, kind, ref)
    sym_test_df = pd.DataFrame(sym_test)
    # zero-fill undefined scores (transitional valve states etc.), identical
    # policy to script 21/26 (Decision 1 of the frozen experiment protocol)
    sym_test_df = sym_test_df.fillna(0.0)

    y_test_full = test_scaled["Label"].to_numpy(dtype=np.float32)
    raw_test_arr = test_scaled[top25].to_numpy(dtype=np.float32)
    sym_test_arr = sym_test_df[STAT_TOP6].to_numpy(dtype=np.float32)

    test_ds = me.MainExperimentDataset("fusion", me.WINDOW, y_test_full, raw_test_arr, sym_test_arr)
    test_loader = DataLoader(test_ds, batch_size=me.BATCH_SIZE, shuffle=False, num_workers=0)

    model = me.FusionModel(raw_input_size=len(top25), symbolic_input_size=len(STAT_TOP6),
                            hidden_size=me.HIDDEN_SIZE, num_layers=me.NUM_LAYERS, dropout=me.DROPOUT)
    ckpt_path = RESULTS_DIR / f"stat_top6_seed{seed}_checkpoint.pt"
    model.load_state_dict(torch.load(ckpt_path, map_location="cpu"))
    model.eval()

    all_probs, all_labels = [], []
    with torch.no_grad():
        for batch in test_loader:
            logits, yb = fusion_fwd(model, batch)
            all_probs.append(torch.sigmoid(logits).numpy())
            all_labels.append(yb.numpy())
    y_prob = np.concatenate(all_probs)
    y_true = np.concatenate(all_labels)
    y_pred = (y_prob >= threshold).astype(int)
    metrics = me.compute_metrics(y_true, y_pred, y_prob)
    latency = me.measure_latency_ms_per_sequence(model, test_loader, fusion_fwd)

    prefix = RESULTS_DIR / f"stat_top6_seed{seed}_test"
    pd.DataFrame({"y_true": y_true, "y_prob": y_prob}).to_csv(f"{prefix}_predictions.csv", index=False)
    test_meta = {"model_name": "stat_top6", "seed": seed, "threshold_source": str(RESULTS_DIR / f"stat_top6_seed{seed}_metadata.json"),
                 "selected_threshold": float(threshold), "latency_ms_per_sequence": latency,
                 "n_test_sequences": len(y_true), "metrics": metrics}
    with open(f"{prefix}_metadata.json", "w", encoding="utf-8") as f:
        json.dump(test_meta, f, indent=2, default=str)
    log(f"  seed {seed}: TEST MCC={metrics['MCC']:.4f} F1={metrics['F1']:.4f} AUC={metrics['ROC_AUC']:.4f}")
    return test_meta


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--run", action="store_true",
                         help="Run the full protocol: train 5 seeds, select VALIDATION thresholds, "
                              "then evaluate TEST for all 5 seeds, then aggregate.")
    args = parser.parse_args()

    section("MATCHED CONTROL EXPERIMENT — STATISTICAL-TOP-6")
    log(f"Run start: {RUN_START.isoformat()}")
    log(f"Mode: {'FULL RUN' if args.run else 'PREFLIGHT + VERIFICATION ONLY'}")

    pf = run_preflight()
    if not pf["all_passed"]:
        section("PREFLIGHT/VERIFICATION FAILED — ABORTING BEFORE ANY TRAINING")
        sys.exit(1)

    if not args.run:
        section("PREFLIGHT + VERIFICATION PASSED — STOPPING HERE (pass --run for the full protocol)")
        return

    section("PHASE 1 — TRAINING 5 SEEDS + VALIDATION THRESHOLD SELECTION")
    pf23 = pf["pf23"]
    train_df = pf23["train_df"]
    y_train_full = train_df["Label"].to_numpy(dtype=np.float32)
    train_seq_labels = y_train_full[me.WINDOW - 1:]
    n_pos, n_neg = float((train_seq_labels == 1).sum()), float((train_seq_labels == 0).sum())
    pos_weight = torch.tensor(n_neg / n_pos, dtype=torch.float32)
    log(f"pos_weight (TRAIN sequence labels only) = {pos_weight.item():.6f} (identical for every seed/model)")

    val_metas = {}
    for seed in SEEDS:
        meta_path = RESULTS_DIR / f"stat_top6_seed{seed}_metadata.json"
        if meta_path.exists():
            with open(meta_path, encoding="utf-8") as f:
                val_metas[seed] = json.load(f)
            log(f"  seed {seed}: already trained, resuming from {meta_path.name}")
            continue
        log(f"\n--- Training seed {seed} ---")
        val_metas[seed] = train_one_seed(seed, pf, pos_weight)

    section("PHASE 2 — TEST EVALUATION (one-shot per seed, after VALIDATION threshold is frozen)")
    test_metas = {}
    for seed in SEEDS:
        tmeta_path = RESULTS_DIR / f"stat_top6_seed{seed}_test_metadata.json"
        if tmeta_path.exists():
            with open(tmeta_path, encoding="utf-8") as f:
                test_metas[seed] = json.load(f)
            log(f"  seed {seed}: TEST already evaluated, resuming from {tmeta_path.name}")
            continue
        log(f"\n--- Evaluating TEST, seed {seed} ---")
        test_metas[seed] = evaluate_test_one_seed(seed, pf, val_metas[seed])

    section("PHASE 3 — AGGREGATION")
    rows = []
    for seed in SEEDS:
        vm, tm = val_metas[seed]["metrics"], test_metas[seed]["metrics"]
        rows.append({
            "Model": "stat_top6", "Seed": seed,
            "VAL_MCC": vm["MCC"], "VAL_F1": vm["F1"], "VAL_ROC_AUC": vm["ROC_AUC"],
            "TEST_MCC": tm["MCC"], "TEST_F1": tm["F1"], "TEST_ROC_AUC": tm["ROC_AUC"],
            "Selected_Threshold": val_metas[seed]["selected_threshold"],
        })
    out_df = pd.DataFrame(rows)
    out_path = TABLES_OUT_DIR / "stat_top6_results_long.csv"
    out_df.to_csv(out_path, index=False)
    log(f"Wrote {out_path}")
    log(out_df.to_string(index=False))

    log("\nRUN COMPLETE.")


if __name__ == "__main__":
    main()
